version: "3"
services:

  web:
    image: golosblockchain/ui-auth:latest
    restart: always
    build: .    
    volumes:
      - ./config/default.json:/var/app/config/default.json
      - ./config/oauth.json:/var/app/config/oauth.json
      - ./themes:/var/app/themes
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SDC_TARANTOOL_HOSTNAME: db
      SDC_CLIENT_WEBSOCKET_URL: https://api-full.golos.id
      SDC_SERVER_WEBSOCKET_URL: https://api-full.golos.id
      
  # other parameters in config/custom-environment-variables.json

  db:
    image: golosblockchain/ui-auth:tarantool
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - ./tarantool:/var/lib/tarantool
